-- 007_weather_ai_analyses.sql — 预设目的地 DeepSeek 天气分析共享缓存
--
-- 每个 preset_id + ECMWF 数据版本 + 分析模板版本只生成一次。
-- 浏览器角色无任何权限；仅 Vercel Function 使用 service_role 读写。

CREATE TABLE IF NOT EXISTS public.weather_ai_analyses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preset_id text NOT NULL CHECK (preset_id IN (
    'sanya', 'lingshui', 'haitang', 'wanning', 'houhai',
    'chengdu', 'jiang-an', 'wangjiang', 'leshan', 'emeishan', 'jiuzhaigou', 'dujiangyan'
  )),
  model_version bigint NOT NULL CHECK (model_version > 0),
  analysis_version text NOT NULL CHECK (char_length(analysis_version) BETWEEN 1 AND 40),
  status text NOT NULL DEFAULT 'generating' CHECK (status IN ('generating', 'ready', 'failed')),
  analyses jsonb,
  prompt_tokens integer NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
  completion_tokens integer NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
  error_code text,
  generated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (preset_id, model_version, analysis_version),
  CHECK ((status = 'ready' AND analyses IS NOT NULL) OR status <> 'ready')
);

ALTER TABLE public.weather_ai_analyses ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.weather_ai_analyses FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON TABLE public.weather_ai_analyses TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.weather_ai_analyses_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.touch_weather_ai_analysis()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.touch_weather_ai_analysis() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.touch_weather_ai_analysis() TO service_role;

DROP TRIGGER IF EXISTS touch_weather_ai_analysis ON public.weather_ai_analyses;
CREATE TRIGGER touch_weather_ai_analysis
  BEFORE UPDATE ON public.weather_ai_analyses
  FOR EACH ROW EXECUTE FUNCTION public.touch_weather_ai_analysis();

-- 原子抢占生成权：新版本首次请求、失败记录或超过 5 分钟的僵尸任务可取得租约。
CREATE OR REPLACE FUNCTION public.claim_weather_ai_analysis(
  p_preset_id text,
  p_model_version bigint,
  p_analysis_version text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  claimed_id bigint;
BEGIN
  INSERT INTO public.weather_ai_analyses (
    preset_id, model_version, analysis_version, status, analyses, error_code
  ) VALUES (
    p_preset_id, p_model_version, p_analysis_version, 'generating', NULL, NULL
  )
  ON CONFLICT (preset_id, model_version, analysis_version) DO UPDATE
    SET status = 'generating', analyses = NULL, error_code = NULL,
        prompt_tokens = 0, completion_tokens = 0, generated_at = NULL
    WHERE weather_ai_analyses.status = 'failed'
       OR weather_ai_analyses.updated_at < now() - interval '5 minutes'
  RETURNING id INTO claimed_id;

  RETURN claimed_id IS NOT NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_weather_ai_analysis(text, bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_weather_ai_analysis(text, bigint, text) TO service_role;

NOTIFY pgrst, 'reload schema';

-- 生产自检：以下查询应均返回 false / false / false。
-- SELECT
--   has_table_privilege('anon', 'public.weather_ai_analyses', 'SELECT') AS anon_can_read,
--   has_table_privilege('authenticated', 'public.weather_ai_analyses', 'SELECT') AS user_can_read,
--   has_function_privilege('authenticated', 'public.claim_weather_ai_analysis(text,bigint,text)', 'EXECUTE') AS user_can_claim;
